/******************************************************************************************/
/******************************************************************************************/
/******************************     Name   :  Abir Omara     ******************************/
/******************************     Date   :  8/1/2023       ******************************/
/******************************     SWC    :  TIMERS         ******************************/
/******************************   Version  :  1.0            ******************************/
/******************************************************************************************/
/******************************************************************************************/

/* Lib layer */
#include "STD_TYPES.h"
#include "BIT_MATH.h"

/* MCAL */
#include "TIMERS_interface.h"
#include "TIMERS_private.h"
#include "TIMERS_config.h"

/*Global Pointer to function of Timer0 OVF*/
static void (*TIMERS_pfTimer0OVF)(void)= NULL;
/*Global Pointer to function of Timer0 CTC*/
static void (*TIMERS_pfTimer0CTC)(void)= NULL;

/*Global Pointer to function of Timer1 OVF*/
static void (*TIMERS_pfTimer1OVF)(void)= NULL;
/*Global Pointer to function of Timer1 CTC*/
static void (*TIMERS_pfTimer1CTCA)(void)= NULL;

/*Global Pointer to function of Timer2 OVF*/
static void (*TIMERS_pfTimer2OVF)(void)= NULL;
/*Global Pointer to function of Timer2 CTC*/
static void (*TIMERS_pfTimer2CTC)(void)= NULL;

void TIMERS_voidTimer0Init (void)
{
	/*select timer mode */
#if TIMER0_MODE==TIMER_NORMAL_MODE
	CLR_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_WGM01);
	CLR_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_WGM00);
	/*Set Preload Value*/
	TIMERS_u8_TCNT0 =TIMER0_u8_PRELOAD_VALUE;
#elif TIMER0_MODE==TIMER_PHASE_CORRECT_PWM
	CLR_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_WGM01);
	SET_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_WGM00);
#elif TIMER0_MODE==TIMER_CTC_MODE
	SET_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_WGM01);
	CLR_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_WGM00);
	/*Set Compare match unit register Value*/
	TIMERS_u8_OCR0 =TIMER_u8_OCR0_INIT_VALUE;
#elif TIMER0_MODE==TIMER_FAST_PWM
	SET_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_WGM01);
	SET_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_WGM00);
#endif
	/*select oc0 mode */
#if TIMER_u8_OC0_PIN_MODE==TIMER_u8_OCX_DISCONNECTED
	CLR_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_COM01);
	CLR_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_COM00);
#elif TIMER_u8_OC0_PIN_MODE==TIMER_u8_OCX_TOGGELE_Reserved
	CLR_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_COM01);
	SET_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_COM00);
#elif TIMER_u8_OC0_PIN_MODE==TIMER_u8_OCX_SET_NON_INVERTED
	SET_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_COM01);
	CLR_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_COM00);
#elif TIMER_u8_OC0_PIN_MODE==TIMER_u8_OCX_CLEAR_INVERTED
	SET_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_COM01);
	SET_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_COM00);
#endif
	/*enable or disable OVF interrupt*/
#if TIMER0_OVF_INTERRUPT_INIT==TIMER_INTERRUPT_ENABLE
	SET_BIT(TIMERS_u8_TIMSK,TIMERS_u8_TIMSK_TOIE0);
#elif TIMER0_OVF_INTERRUPT_INIT==TIMER_INTERRUPT_DISABLE
	CLR_BIT(TIMERS_u8_TIMSK,TIMERS_u8_TIMSK_TOIE0);
#endif
	/*enable or disable CTC interrupt*/
#if TIMER0_CTC_INTERRUPT_INIT==TIMER_INTERRUPT_ENABLE
	SET_BIT(TIMERS_u8_TIMSK,TIMERS_u8_TIMSK_OCIE0);
#elif TIMER0_CTC_INTERRUPT_INIT==TIMER_INTERRUPT_DISABLE
	CLR_BIT(TIMERS_u8_TIMSK,TIMERS_u8_TIMSK_OCIE0);
#endif
	/*select clk prescaler*/
#if TIMER0_CLOCK_SOURCE==TIMER_CLOCK_NO_CLOCK
	CLR_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_CS02);
	CLR_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_CS01);
	CLR_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_CS00);
#elif TIMER0_CLOCK_SOURCE==TIMER_CLOCK_NO_PRESCHALER
	CLR_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_CS02);
	CLR_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_CS01);
	SET_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_CS00);
#elif TIMER0_CLOCK_SOURCE==TIMER_CLOCK_8_PRESCHALER
	CLR_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_CS02);
	SET_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_CS01);
	CLR_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_CS00);
#elif TIMER0_CLOCK_SOURCE==TIMER_CLOCK_64_PRESCHALER
	CLR_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_CS02);
	SET_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_CS01);
	SET_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_CS00);
#elif TIMER0_CLOCK_SOURCE==TIMER_CLOCK_256_PRESCHALER
	SET_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_CS02);
	CLR_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_CS01);
	CLR_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_CS00);
#elif TIMER0_CLOCK_SOURCE==TIMER_CLOCK_1024_PRESCHALER
	SET_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_CS02);
	CLR_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_CS01);
	SET_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_CS00);
#elif TIMER0_CLOCK_SOURCE==TIMER_CLOCK_EXTERNAL_FALLING_EDGE
	SET_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_CS02);
	SET_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_CS01);
	CLR_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_CS00);
#elif TIMER0_CLOCK_SOURCE==TIMER_CLOCK_EXTERNAL_RISING_EDGE
	SET_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_CS02);
	SET_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_CS01);
	SET_BIT(TIMERS_u8_TCCR0,TIMERS_u8_TCCR0_CS00);
#endif

}
void TIMERS_voidTimer1Init (void)
{

#if TIMER1_MODE==TIMER_NORMAL
	CLR_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_WGM13);
	CLR_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_WGM12);
	CLR_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_WGM11);
	CLR_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_WGM10);
	/*Set Preload Value*/
	TIMERS_u16_TCNT1 =TIMER1_u16_PRELOAD_VALUE;
#elif TIMER1_MODE==TIMER_PHASE_CORRECT_PWM_8bit
	CLR_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_WGM13);
	CLR_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_WGM12);
	CLR_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_WGM11);
	SET_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_WGM10);
#elif TIMER1_MODE==TIMER_PHASE_CORRECT_PWM_9bit
	CLR_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_WGM13);
	CLR_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_WGM12);
	SET_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_WGM11);
	CLR_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_WGM10);
#elif TIMER1_MODE==TIMER_PHASE_CORRECT_PWM_10bit
	CLR_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_WGM13);
	CLR_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_WGM12);
	SET_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_WGM11);
	SET_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_WGM10);
#elif TIMER1_MODE==TIMER_CTC_OCR1A
	CLR_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_WGM13);
	SET_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_WGM12);
	CLR_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_WGM11);
	CLR_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_WGM10);
#elif TIMER1_MODE==TIMER_FAST_PWM_8bit
	CLR_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_WGM13);
	SET_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_WGM12);
	CLR_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_WGM11);
	SET_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_WGM10);
#elif TIMER1_MODE==TIMER_FAST_PWM_9bit
	CLR_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_WGM13);
	SET_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_WGM12);
	SET_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_WGM11);
	CLR_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_WGM10);
#elif TIMER1_MODE==TIMER_FAST_PWM_10bit
	CLR_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_WGM13);
	SET_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_WGM12);
	SET_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_WGM11);
	SET_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_WGM10);
#elif TIMER1_MODE==TIMER_PHASEandFREUENCY_CORRECT_ICR1
	SET_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_WGM13);
	CLR_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_WGM12);
	CLR_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_WGM11);
	CLR_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_WGM10);
#elif TIMER1_MODE==TIMER_PHASEandFREUENCY_CORRECT_OCR1A
	SET_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_WGM13);
	CLR_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_WGM12);
	CLR_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_WGM11);
	SET_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_WGM10);
#elif TIMER1_MODE==TIMER_PHASE_CORRECT_ICR1
	SET_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_WGM13);
	CLR_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_WGM12);
	SET_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_WGM11);
	CLR_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_WGM10);
#elif TIMER1_MODE==TIMER_PHASE_CORRECT_OCR1A
	SET_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_WGM13);
	CLR_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_WGM12);
	SET_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_WGM11);
	SET_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_WGM10);
#elif TIMER1_MODE==TIMER_CTC_ICR1
	SET_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_WGM13);
	SET_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_WGM12);
	CLR_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_WGM11);
	CLR_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_WGM10);
#elif TIMER1_MODE==TIMER_FAST_PWM_ICR1
	SET_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_WGM13);
	SET_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_WGM12);
	SET_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_WGM11);
	CLR_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_WGM10);
#elif TIMER1_MODE==TIMER_FAST_PWM_OCR1A
	SET_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_WGM13);
	SET_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_WGM12);
	SET_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_WGM11);
	SET_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_WGM10);
#endif
	/*Select hardware action on OC1A*/
#if TIMER_u8_OC1A_PIN_MODE==TIMER_u8_OCX_DISCONNECTED
	CLR_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_COM1A1);
	CLR_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_COM1A0);
#elif TIMER_u8_OC1A_PIN_MODE==TIMER_u8_OCX_TOGGELE_Reserved
	CLR_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_COM1A1);
	CLR_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_COM1A0);
#elif TIMER_u8_OC1A_PIN_MODE==TIMER_u8_OCX_SET_NON_INVERTED
	SET_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_COM1A1);
	CLR_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_COM1A0);
#elif TIMER_u8_OC1A_PIN_MODE==TIMER_u8_OCX_CLEAR_INVERTED
	SET_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_COM1A1);
	SET_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_COM1A0);
#endif

	/*Select hardware action on OC1B*/
#if TIMER_u8_OC1B_PIN_MODE==TIMER_u8_OCX_DISCONNECTED
	CLR_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_COM1B1);
	CLR_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_COM1B0);
#elif TIMER_u8_OC1B_PIN_MODE==TIMER_u8_OCX_TOGGELE_Reserved
	CLR_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_COM1B1);
	CLR_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_COM1B0);
#elif TIMER_u8_OC1B_PIN_MODE==TIMER_u8_OCX_SET_NON_INVERTED
	SET_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_COM1B1);
	CLR_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_COM1B0);
#elif TIMER_u8_OC1B_PIN_MODE==TIMER_u8_OCX_CLEAR_INVERTED
	SET_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_COM1B1);
	SET_BIT(TIMERS_u8_TCCR1A,TIMERS_u8_TCCR1A_COM1B0);
#endif

	/*enable or disable OVF interrupt*/
#if TIMER1_OVF_INTERRUPT_INIT==TIMER_INTERRUPT_ENABLE
	SET_BIT(TIMERS_u8_TIMSK,TIMERS_u8_TIMSK_TOIE1);
#elif TIMER1_OVF_INTERRUPT_INIT==TIMER_INTERRUPT_DISABLE
	CLR_BIT(TIMERS_u8_TIMSK,TIMERS_u8_TIMSK_TOIE1);
#endif
	/*enable or disable CTC A interrupt*/
#if TIMER1_CTC_CHANNEL_A_INTERRUPT_INIT==TIMER_INTERRUPT_ENABLE
	SET_BIT(TIMERS_u8_TIMSK,TIMERS_u8_TIMSK_OCIE1A);
#elif TIMER1_CTC_CHANNEL_A_INTERRUPT_INIT==TIMER_INTERRUPT_DISABLE
	CLR_BIT(TIMERS_u8_TIMSK,TIMERS_u8_TIMSK_OCIE1A);
#endif

	/*enable or disable CTC B interrupt*/
#if TIMER1_CTC_CHANNEL_B_INTERRUPT_INIT==TIMER_INTERRUPT_ENABLE
	SET_BIT(TIMERS_u8_TIMSK,TIMERS_u8_TIMSK_OCIE1B);
#elif TIMER1_CTC_CHANNEL_B_INTERRUPT_INIT==TIMER_INTERRUPT_DISABLE
	CLR_BIT(TIMERS_u8_TIMSK,TIMERS_u8_TIMSK_OCIE1B);
#endif


	/*Set Top Value on ICR1 */
	TIMERS_u16_ICR1=TIMER1_u16_ICR1_VALUE;

	/*Set angle of servo Motor */
	TIMERS_u16_OCR1A=TIMER_u16_OCR1A_INIT_VALUE;
	/*select clk prescaler*/
#if TIMER1_CLOCK_SOURCE==TIMER_CLOCK_NO_CLOCK
	CLR_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_CS12);
	CLR_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_CS11);
	CLR_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_CS10);
#elif TIMER1_CLOCK_SOURCE==TIMER_CLOCK_NO_PRESCHALER
	CLR_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_CS12);
	CLR_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_CS11);
	SET_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_CS10);
#elif TIMER1_CLOCK_SOURCE==TIMER_CLOCK_8_PRESCHALER
	CLR_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_CS12);
	SET_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_CS11);
	CLR_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_CS10);
#elif TIMER1_CLOCK_SOURCE==TIMER_CLOCK_64_PRESCHALER
	CLR_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_CS12);
	SET_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_CS11);
	SET_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_CS10);
#elif TIMER1_CLOCK_SOURCE==TIMER_CLOCK_256_PRESCHALER
	SET_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_CS12);
	CLR_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_CS11);
	CLR_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_CS10);
#elif TIMER1_CLOCK_SOURCE==TIMER_CLOCK_1024_PRESCHALER
	SET_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_CS12);
	CLR_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_CS11);
	SET_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_CS10);
#elif TIMER1_CLOCK_SOURCE==TIMER_CLOCK_EXTERNAL_FALLING_EDGE
	SET_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_CS12);
	SET_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_CS11);
	CLR_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_CS10);
#elif TIMER1_CLOCK_SOURCE==TIMER_CLOCK_EXTERNAL_RISING_EDGE
	SET_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_CS12);
	SET_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_CS11);
	SET_BIT(TIMERS_u8_TCCR1B,TIMERS_u8_TCCR1B_CS10);
#endif
}
void TIMERS_voidTimer2Init (void)
{
	/*select timer mode */
#if TIMER2_MODE==TIMER_NORMAL_MODE
	CLR_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_WGM21);
	CLR_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_WGM20);
	/*Set Preload Value*/
	TIMERS_u8_TCNT2 =TIMER2_u8_PRELOAD_VALUE;
#elif TIMER2_MODE==TIMER_PHASE_CORRECT_PWM
	CLR_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_WGM21);
	SET_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_WGM20);
#elif TIMER2_MODE==TIMER_CTC_MODE
	SET_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_WGM21);
	CLR_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_WGM20);
	/*Set Compare match unit register Value*/
	TIMERS_u8_OCR2 =TIMER_u8_OCR2_INIT_VALUE;
#elif TIMER2_MODE==TIMER_FAST_PWM
	SET_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_WGM21);
	SET_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_WGM20);
#endif
	/*select oc2 mode */
#if TIMER_u8_OC2_PIN_MODE==TIMER_u8_OCX_DISCONNECTED
	CLR_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_COM21);
	CLR_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_COM20);
#elif TIMER_u8_OC2_PIN_MODE==TIMER_u8_OCX_TOGGELE_Reserved
	CLR_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_COM21);
	SET_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_COM20);
#elif TIMER_u8_OC2_PIN_MODE==TIMER_u8_OCX_SET_NON_INVERTED
	SET_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_COM21);
	CLR_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_COM20);
#elif TIMER_u8_OC2_PIN_MODE==TIMER_u8_OCX_CLEAR_INVERTED
	SET_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_COM21);
	SET_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_COM20);
#endif
	/*enable or disable OVF interrupt*/
#if TIMER2_OVF_INTERRUPT_INIT==TIMER_INTERRUPT_ENABLE
	SET_BIT(TIMERS_u8_TIMSK,TIMERS_u8_TIMSK_TOIE2);
#elif TIMER2_OVF_INTERRUPT_INIT==TIMER_INTERRUPT_DISABLE
	CLR_BIT(TIMERS_u8_TIMSK,TIMERS_u8_TIMSK_TOIE2);
#endif
	/*enable or disable CTC interrupt*/
#if TIMER2_CTC_INTERRUPT_INIT==TIMER_INTERRUPT_ENABLE
	SET_BIT(TIMERS_u8_TIMSK,TIMERS_u8_TIMSK_OCIE2);
#elif TIMER2_CTC_INTERRUPT_INIT==TIMER_INTERRUPT_DISABLE
	CLR_BIT(TIMERS_u8_TIMSK,TIMERS_u8_TIMSK_OCIE2);
#endif

	/*select clk prescaler*/
#if TIMER2_CLOCK_SOURCE==TIMER_CLOCK_NO_CLOCK
	CLR_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_CS22);
	CLR_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_CS21);
	CLR_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_CS20);
#elif TIMER2_CLOCK_SOURCE==TIMER_CLOCK_NO_PRESCHALER
	CLR_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_CS22);
	CLR_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_CS21);
	SET_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_CS20);
#elif TIMER2_CLOCK_SOURCE==TIMER_CLOCK_8_PRESCHALER
	CLR_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_CS22);
	SET_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_CS21);
	CLR_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_CS20);
#elif TIMER2_CLOCK_SOURCE==TIMER_CLOCK_64_PRESCHALER
	CLR_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_CS22);
	SET_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_CS21);
	SET_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_CS20);
#elif TIMER2_CLOCK_SOURCE==TIMER_CLOCK_256_PRESCHALER
	SET_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_CS22);
	CLR_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_CS21);
	CLR_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_CS20);
#elif TIMER2_CLOCK_SOURCE==TIMER_CLOCK_1024_PRESCHALER
	SET_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_CS22);
	CLR_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_CS21);
	SET_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_CS20);
#elif TIMER2_CLOCK_SOURCE==TIMER_CLOCK_EXTERNAL_FALLING_EDGE
	SET_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_CS22);
	SET_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_CS21);
	CLR_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_CS20);
#elif TIMER2_CLOCK_SOURCE==TIMER_CLOCK_EXTERNAL_RISING_EDGE
	SET_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_CS22);
	SET_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_CS21);
	SET_BIT(TIMERS_u8_TCCR2,TIMERS_u8_TCCR2_CS20);
#endif
}
void TIMERS_voidTimer0SetCompareMatchValue (u8 Copy_u8OCR0Value)
{
	TIMERS_u8_OCR0=Copy_u8OCR0Value;
}
void TIMERS_voidTimer1SetCompareMatchValueA (u16 Copy_u16OCR1AValue)
{
	TIMERS_u16_OCR1A=Copy_u16OCR1AValue;
}
void TIMERS_voidTimer2SetCompareMatchValue (u8 Copy_u8OCR2Value)
{
	TIMERS_u8_OCR2=Copy_u8OCR2Value;
}

u8 TIMERS_u8Timer0OVFSetCallBack (void (*Copy_pf)(void))
{
	u8 Local_u8ErrorState = STD_TYPES_OK;
	if (Copy_pf != NULL)
	{
		TIMERS_pfTimer0OVF = Copy_pf;
	}
	else
	{
		Local_u8ErrorState = STD_TYPES_NOK;
	}
	return Local_u8ErrorState;
}
u8 TIMERS_u8Timer1OVFSetCallBack (void (*Copy_pf)(void))
{
	u8 Local_u8ErrorState = STD_TYPES_OK;
	if (Copy_pf != NULL)
	{
		TIMERS_pfTimer1OVF = Copy_pf;
	}
	else
	{
		Local_u8ErrorState = STD_TYPES_NOK;
	}
	return Local_u8ErrorState;
}
u8 TIMERS_u8Timer2OVFSetCallBack (void (*Copy_pf)(void))
{
	u8 Local_u8ErrorState = STD_TYPES_OK;
	if (Copy_pf != NULL)
	{
		TIMERS_pfTimer2OVF = Copy_pf;
	}
	else
	{
		Local_u8ErrorState = STD_TYPES_NOK;
	}
	return Local_u8ErrorState;
}
u8 TIMERS_u8Timer0CTCSetCallBack (void (*Copy_pf)(void))
{

	u8 Local_u8ErrorState = STD_TYPES_OK;
	if (Copy_pf != NULL)
	{
		TIMERS_pfTimer0CTC = Copy_pf;
	}
	else
	{
		Local_u8ErrorState = STD_TYPES_NOK;
	}
	return Local_u8ErrorState;
}
u8 TIMERS_u8Timer1CTCSetCallBack (void (*Copy_pf)(void))
{

	u8 Local_u8ErrorState = STD_TYPES_OK;
	if (Copy_pf != NULL)
	{
		TIMERS_pfTimer1CTCA = Copy_pf;
	}
	else
	{
		Local_u8ErrorState = STD_TYPES_NOK;
	}
	return Local_u8ErrorState;
}
u8 TIMERS_u8Timer2CTCSetCallBack (void (*Copy_pf)(void))
{

	u8 Local_u8ErrorState = STD_TYPES_OK;
	if (Copy_pf != NULL)
	{
		TIMERS_pfTimer2CTC = Copy_pf;
	}
	else
	{
		Local_u8ErrorState = STD_TYPES_NOK;
	}
	return Local_u8ErrorState;
}

/* Prototype for ISR of TIMER0 OVF*/
void __vector_11(void)   __attribute__((signal));
void __vector_11(void)
{
	static u16 Local_u16_CounterOVF=0;
	Local_u16_CounterOVF++;

	if (Local_u16_CounterOVF == TIMER0_u32_NUMBER_OF_OVF)
	{
		/*Update Preload Value */
		TIMERS_u8_TCNT0 =TIMER0_u8_PRELOAD_VALUE;
		/*Clear the OVF counter*/
		Local_u16_CounterOVF=0;
		if (TIMERS_pfTimer0OVF != NULL)
		{
			TIMERS_pfTimer0OVF();
		}
	}
}
/* Prototype for ISR of TIMER1 OVF*/
void __vector_9(void)   __attribute__((signal));
void __vector_9(void)
{
	static u16 Local_u16_CounterOVF=0;
	Local_u16_CounterOVF++;

	if (Local_u16_CounterOVF == TIMER1_u32_NUMBER_OF_OVF)
	{
		/*Update Preload Value */
		TIMERS_u16_TCNT1 =TIMER1_u16_PRELOAD_VALUE;
		/*Clear the OVF counter*/
		Local_u16_CounterOVF=0;
		if (TIMERS_pfTimer1OVF != NULL)
		{
			TIMERS_pfTimer1OVF();
		}
	}
}
/* Prototype for ISR of TIMER2 OVF*/
void __vector_5(void)   __attribute__((signal));
void __vector_5(void)
{
	static u16 Local_u16_CounterOVF=0;
	Local_u16_CounterOVF++;

	if (Local_u16_CounterOVF == TIMER2_u32_NUMBER_OF_OVF)
	{
		/*Update Preload Value */
		TIMERS_u8_TCNT2 =TIMER2_u8_PRELOAD_VALUE;
		/*Clear the OVF counter*/
		Local_u16_CounterOVF=0;
		if (TIMERS_pfTimer2OVF != NULL)
		{
			TIMERS_pfTimer2OVF();
		}
	}
}

/* Prototype for ISR of TIMER0 CTC*/
void __vector_10(void)   __attribute__((signal));
void __vector_10(void)
{
	static u16 Local_u16_CounterCTC=0;
	Local_u16_CounterCTC++;

	if (Local_u16_CounterCTC == TIMER0_u32_NUMBER_OF_CTC)
	{
		/*Clear the CTC counter*/
		Local_u16_CounterCTC=0;

		if (TIMERS_pfTimer0CTC != NULL)
		{
			TIMERS_pfTimer0CTC();
		}
	}
}
/* Prototype for ISR of TIMER1 CTC A*/
void __vector_7(void)   __attribute__((signal));
void __vector_7(void)
{
	static u16 Local_u16_CounterCTC=0;
	Local_u16_CounterCTC++;

	if (Local_u16_CounterCTC == TIMER1_u32_NUMBER_OF_CTC)
	{
		/*Clear the CTC counter*/
		Local_u16_CounterCTC=0;

		if (TIMERS_pfTimer1CTCA != NULL)
		{
			TIMERS_pfTimer1CTCA();
		}
	}
}

/* Prototype for ISR of TIMER0 CTC*/
void __vector_4(void)   __attribute__((signal));
void __vector_4(void)
{
	static u16 Local_u16_CounterCTC=0;
	Local_u16_CounterCTC++;

	if (Local_u16_CounterCTC == TIMER2_u32_NUMBER_OF_CTC)
	{
		/*Clear the CTC counter*/
		Local_u16_CounterCTC=0;

		if (TIMERS_pfTimer2CTC != NULL)
		{
			TIMERS_pfTimer2CTC();
		}
	}
}
